// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhCcq6d_MXmSRuaWeibxHcU1P0WFXyvhs',
    appId: '1:223632904045:web:e86842092e9fa9123cd464',
    messagingSenderId: '223632904045',
    projectId: 'tic-tok-app-7ebc2',
    authDomain: 'tic-tok-app-7ebc2.firebaseapp.com',
    databaseURL: 'https://tic-tok-app-7ebc2-default-rtdb.firebaseio.com',
    storageBucket: 'tic-tok-app-7ebc2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDvZo35XjOuFpe6is6F7p6etbpjAPBQ_U',
    appId: '1:223632904045:android:fa451daf271305fe3cd464',
    messagingSenderId: '223632904045',
    projectId: 'tic-tok-app-7ebc2',
    databaseURL: 'https://tic-tok-app-7ebc2-default-rtdb.firebaseio.com',
    storageBucket: 'tic-tok-app-7ebc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2TSp8pDay6AxwVmoQwkYodQBERQOvbcQ',
    appId: '1:223632904045:ios:8574623ac944556e3cd464',
    messagingSenderId: '223632904045',
    projectId: 'tic-tok-app-7ebc2',
    databaseURL: 'https://tic-tok-app-7ebc2-default-rtdb.firebaseio.com',
    storageBucket: 'tic-tok-app-7ebc2.firebasestorage.app',
    iosClientId: '223632904045-qs4qns65daedkcke8n2ecgrnhj75vgs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );
}
